<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <title>Cetak Label Barcode Harga</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Libre+Barcode+39&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

    <style>
        body {
            font-family: 'Inter', sans-serif;
            background: #f1f5f9;
            color: black;
            margin: 0;
            padding: 10mm;
        }

        .label-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(62mm, 1fr));
            gap: 4mm;
            justify-content: center;
        }

        .label-box {
            width: 62mm;
            height: 38mm;
            border: 1px dashed #475569;
            padding: 2.5mm;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            text-align: center;
            overflow: hidden;
            page-break-inside: avoid;
            background: white;
            border-radius: 4px;
        }

        .store-name {
            font-size: 8pt;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 1.5px;
            border-bottom: 0.5px solid #cbd5e1;
            width: 100%;
            padding-bottom: 0.8mm;
            margin-bottom: 1mm;
            color: #0f172a;
        }

        .product-name {
            font-size: 9.5pt;
            font-weight: 600;
            line-height: 1.25;
            margin-bottom: auto;
            color: #1e293b;
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
            width: 100%;
        }

        .product-price {
            font-size: 13pt;
            font-weight: 700;
            margin: 0.8mm 0;
            color: #0f172a;
        }

        .barcode-wrapper {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 100%;
        }

        .barcode-font {
            font-family: 'Libre Barcode 39', cursive;
            font-size: 34pt;
            line-height: 0.95;
            margin: 0;
            padding: 0;
            color: black;
        }

        .barcode-text {
            font-size: 7.5pt;
            font-weight: 600;
            margin-top: -1mm;
            letter-spacing: 2px;
            color: #475569;
            text-transform: uppercase;
        }

        /* Printable area override */
        @media print {
            body {
                background: white;
                padding: 0;
                margin: 0;
            }

            .no-print {
                display: none !important;
            }

            .label-box {
                border: 1px solid #000; /* Solid border for cutting labels when printed */
                box-shadow: none;
                border-radius: 0;
            }
        }
    </style>
</head>

<body>

    {{-- PRINT BAR HEADER (VISIBLE ON SCREEN ONLY) --}}
    <div class="no-print container-fluid mb-4 py-3 bg-white border border-bottom shadow-sm rounded-3 d-flex justify-content-between align-items-center">
        <div>
            <h5 class="fw-bold mb-1"><i class="fas fa-print me-2 text-primary"></i>Pratinjau Cetak Label Harga</h5>
            <small class="text-muted">Gunakan tombol cetak di sebelah kanan untuk menyimpan sebagai PDF atau langsung print.</small>
        </div>
        <div class="d-flex gap-2">
            <button class="btn btn-secondary py-2 px-3" onclick="window.close()">
                <i class="fas fa-times me-1"></i> Tutup Halaman
            </button>
            <button class="btn btn-primary py-2 px-4 shadow" onclick="window.print()">
                <i class="fas fa-print me-1"></i> Cetak Label
            </button>
        </div>
    </div>

    {{-- THE LABELS GRID --}}
    <div class="label-grid" id="label-container">
        <!-- Labels generated by JS -->
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const data = JSON.parse(localStorage.getItem('barcode_print_data')) || [];
            const container = document.getElementById('label-container');
            const businessName = "{{ $businessName }}";

            if (data.length === 0) {
                container.innerHTML = `
                    <div class="alert alert-warning w-100 mt-4 no-print text-center">
                        <i class="fas fa-exclamation-triangle me-2"></i>Tidak ada data label untuk dicetak. Silakan pilih produk terlebih dahulu.
                    </div>`;
                return;
            }

            data.forEach(item => {
                const qty = parseInt(item.qty) || 1;
                for (let i = 0; i < qty; i++) {
                    const label = document.createElement('div');
                    label.className = 'label-box';
                    
                    // Format code for Code 39: alphanumeric only, must be wrapped in asterisks
                    const cleanCode = item.id.replace(/[^a-zA-Z0-9]/g, '');
                    const barcodeValue = `*${cleanCode}*`;

                    label.innerHTML = `
                        <div class="store-name">${businessName}</div>
                        <div class="product-name">${item.name}</div>
                        <div class="product-price">Rp ${new Intl.NumberFormat('id-ID').format(item.price)}</div>
                        <div class="barcode-wrapper">
                            <div class="barcode-font">${barcodeValue}</div>
                            <div class="barcode-text">${item.id}</div>
                        </div>
                    `;
                    container.appendChild(label);
                }
            });

            // Automatically open printer dialog after a brief delay to ensure font loads
            setTimeout(() => {
                window.print();
            }, 800);
        });
    </script>
</body>

</html>
